# Generated by Django 5.0.6 on 2024-06-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('123', models.CharField(max_length=20, verbose_name='123')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=20)),
                ('adult', models.BooleanField()),
            ],
        ),
    ]
