# Generated by Django 5.0.6 on 2024-06-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='123',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default='M', max_length=20),
            preserve_default=False,
        ),
    ]
