# Generated by Django 5.0.6 on 2024-08-19 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kaspi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedMagazin',
            fields=[
            ],
            options={
                'ordering': ['-create_date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('kaspi.magazin',),
        ),
        migrations.AddField(
            model_name='good',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='magazin',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
