# Generated by Django 5.0.6 on 2024-08-21 15:57

import django.contrib.postgres.fields.ranges
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaspi', '0002_sortedmagazin_good_create_date_magazin_description_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='magazin',
            managers=[
                ('custom_q_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='active_in',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=('2021-01-01', '2021-04-01'), verbose_name='Активно в промежутке'),
        ),
        migrations.AddField(
            model_name='magazin',
            name='active_in',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=('2021-01-01', '2021-04-01'), verbose_name='Активно в промежутке'),
        ),
    ]
