# Generated by Django 5.0.6 on 2024-08-28 14:42

import django.contrib.postgres.fields.ranges
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kaspi', '0003_alter_magazin_managers_good_active_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='active_in',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=(django.utils.timezone.now, '2024-12-12'), verbose_name='Активно в промежутке'),
        ),
        migrations.AlterField(
            model_name='magazin',
            name='active_in',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=(django.utils.timezone.now, '2024-12-12'), verbose_name='Активно в промежутке'),
        ),
    ]
