# Generated by Django 5.0.6 on 2024-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
