# Generated by Django 5.0.6 on 2024-06-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
