# Generated by Django 5.0.6 on 2024-06-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('I', 'Ilyas')], default='O', max_length=100),
            preserve_default=False,
        ),
    ]
