# Generated by Django 5.0.6 on 2024-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_qtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('I', 'Ilyas')], help_text='ПАМАГИ!', max_length=100, verbose_name='Question name'),
        ),
    ]
