# Generated by Django 5.0.6 on 2024-08-28 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_choice_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('FT', 'Feet'), ('SM', 'Santimeter'), ('MM', 'Millimter')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choices_two', to='polls.question'),
        ),
    ]
