# Generated by Django 5.0.6 on 2024-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='profile_cv')),
                ('photo', models.ImageField(upload_to='profile_photo')),
            ],
        ),
    ]
